export { jeopardyVersions as jeopardy } from './jeopardyVersions';
export { pyramidVersions as pyramid } from './pyramidVersions';
export { wheelVersions as wheel } from './wheelVersions';
export { familyFeudVersions as familyFeud } from './familyFeudVersions';
export { nameThatTuneVersions as nameThatTune } from './nameThatTuneVersions';
export { whatTheHellIsItVersions as whatTheHellIsIt } from './whatTheHellIsItVersions';
export { newlywedVersions as newlywed } from './newlywedVersions';
export { couplesVersions as couples } from './couplesVersions';
export { espVersions as esp } from './espVersions';
