export const jeopardyVersions = [
	{
		title: 'Version 1',
		rating: 'r',
		content: [
			{
				category: 'Category One v1',
				questions: [
					{
						value: 100,
						type: 'video',
						question: 'jeopardyvideoquestion.mp4',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: true,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: true,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Two',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Three',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Four',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Five',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
		],
	},
	{
		title: 'Version 2',
		rating: 'pg13',
		content: [
			{
				category: 'Category One v2',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Two',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Three',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Four',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Five',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
		],
	},
	{
		title: 'Version 3',
		rating: 'kids',
		content: [
			{
				category: 'Category One v3',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Two',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Three',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Four',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
			{
				category: 'Category Five',
				questions: [
					{
						value: 100,
						type: 'text',
						question: 'Test Question 1',
						answer: 'Test Answer 1',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 200,
						type: 'text',
						question: 'Test Question 2',
						answer: 'Test Answer 2',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 300,
						type: 'text',
						question: 'Test Question 3',
						answer: 'Test Answer 3',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 400,
						type: 'text',
						question: 'Test Question 4',
						answer: 'Test Answer 4',
						completed: false,
						dailyDouble: false,
					},
					{
						value: 500,
						type: 'text',
						question: 'Test Question 5',
						answer: 'Test Answer 5',
						completed: false,
						dailyDouble: false,
					},
				],
			},
		],
	},
];
